// Department classification dictionary and classifier.
//
// Maps a Hebrew item name (free text or product name) to one of the
// supermarket departments below. The dictionary is curated by hand —
// no LLM call at runtime. User corrections are stored separately in
// `shopping.user_department_overrides` (added in migration 0013).

export const DEPARTMENT_CODES = {
  PRODUCE: 'produce',
  BAKERY: 'bakery',
  DAIRY: 'dairy',
  MEAT_FISH: 'meat_fish',
  DELI: 'deli',
  PANTRY: 'pantry',
  SNACKS: 'snacks',
  BEVERAGES: 'beverages',
  ALCOHOL: 'alcohol',
  FROZEN: 'frozen',
  CLEANING: 'cleaning',
  PERSONAL_CARE: 'personal_care',
  BABY: 'baby',
  UNCLASSIFIED: 'unclassified',
} as const;

export type DepartmentCode = (typeof DEPARTMENT_CODES)[keyof typeof DEPARTMENT_CODES];

export interface DepartmentMeta {
  code: DepartmentCode;
  name: string;        // Hebrew display name
  order: number;       // Shopping-route order; lower = earlier in the store
}

export const DEPARTMENTS: DepartmentMeta[] = [
  { code: DEPARTMENT_CODES.PRODUCE,       name: 'ירקות ופירות',  order: 1 },
  { code: DEPARTMENT_CODES.BAKERY,        name: 'מאפייה',        order: 2 },
  { code: DEPARTMENT_CODES.DAIRY,         name: 'חלב וביצים',    order: 3 },
  { code: DEPARTMENT_CODES.MEAT_FISH,     name: 'בשר ועוף ודגים', order: 4 },
  { code: DEPARTMENT_CODES.DELI,          name: 'דליקטסן',       order: 5 },
  { code: DEPARTMENT_CODES.PANTRY,        name: 'יבשים ומזווה',  order: 6 },
  { code: DEPARTMENT_CODES.SNACKS,        name: 'חטיפים ומתוקים', order: 7 },
  { code: DEPARTMENT_CODES.BEVERAGES,     name: 'משקאות',        order: 8 },
  { code: DEPARTMENT_CODES.ALCOHOL,       name: 'אלכוהול',       order: 9 },
  { code: DEPARTMENT_CODES.FROZEN,        name: 'קפואים',        order: 10 },
  { code: DEPARTMENT_CODES.CLEANING,      name: 'ניקיון',        order: 11 },
  { code: DEPARTMENT_CODES.PERSONAL_CARE, name: 'פארם וטיפוח',   order: 12 },
  { code: DEPARTMENT_CODES.BABY,          name: 'תינוקות',       order: 13 },
  { code: DEPARTMENT_CODES.UNCLASSIFIED,  name: 'לא מסווג',      order: 99 },
];

export const DEPARTMENT_BY_CODE: Record<DepartmentCode, DepartmentMeta> = Object.fromEntries(
  DEPARTMENTS.map((d) => [d.code, d]),
) as Record<DepartmentCode, DepartmentMeta>;

// ---------------------------------------------------------------------------
// Keyword rules
//
// A rule matches if its `match` string is found anywhere in the (normalized)
// item name. To avoid false positives:
//   - `exclude` cancels the rule if any listed substring is also present.
//   - `priority` (default 0) wins on conflict; otherwise the longer match wins.
//
// Keep rules ordered by department so the file remains scannable. Within a
// department, prefer the most common terms first.
// ---------------------------------------------------------------------------

interface Rule {
  match: string;
  dept: DepartmentCode;
  exclude?: string[];
  priority?: number;
}

const D = DEPARTMENT_CODES;

const RULES: Rule[] = [
  // ============================================================
  // ירקות ופירות
  // ============================================================
  // ירקות
  { match: 'עגבני', dept: D.PRODUCE },
  { match: 'מלפפון', dept: D.PRODUCE },
  { match: 'פלפל', dept: D.PRODUCE, exclude: ['פלפל שחור', 'פלפל לבן', 'פפריקה'] },
  { match: 'בצל', dept: D.PRODUCE },
  { match: 'שום', dept: D.PRODUCE, exclude: ['שומשום', 'שומן'] },
  { match: 'גזר', dept: D.PRODUCE },
  { match: 'תפוח אדמה', dept: D.PRODUCE, priority: 2 },
  { match: "תפו''א", dept: D.PRODUCE, priority: 2 },
  { match: 'תפוא', dept: D.PRODUCE, priority: 2 },
  { match: 'בטטה', dept: D.PRODUCE },
  { match: 'חציל', dept: D.PRODUCE },
  { match: 'קישוא', dept: D.PRODUCE },
  { match: 'דלעת', dept: D.PRODUCE },
  { match: 'דלורית', dept: D.PRODUCE },
  { match: 'כרוב', dept: D.PRODUCE },
  { match: 'כרובית', dept: D.PRODUCE, priority: 1 },
  { match: 'ברוקולי', dept: D.PRODUCE },
  { match: 'חסה', dept: D.PRODUCE },
  { match: 'תרד', dept: D.PRODUCE },
  { match: 'מנגולד', dept: D.PRODUCE },
  { match: 'סלרי', dept: D.PRODUCE },
  { match: 'פטרוזיל', dept: D.PRODUCE },
  { match: 'כוסבר', dept: D.PRODUCE },
  { match: 'שמיר', dept: D.PRODUCE },
  { match: 'נענע', dept: D.PRODUCE },
  { match: 'בזיליק', dept: D.PRODUCE },
  { match: 'רוקט', dept: D.PRODUCE },
  { match: 'ארוגולה', dept: D.PRODUCE },
  { match: 'צנון', dept: D.PRODUCE },
  { match: 'לפת', dept: D.PRODUCE },
  { match: 'קולרבי', dept: D.PRODUCE },
  { match: 'תירס', dept: D.PRODUCE, exclude: ['קמח תירס', 'שמן תירס', 'פצפוצי תירס', 'דגני תירס', 'קורנפלקס'] },
  { match: 'אפונה', dept: D.PRODUCE, exclude: ['אפונה קפואה', 'שימורי אפונה'] },
  { match: 'שעועית ירוקה', dept: D.PRODUCE, priority: 2 },
  { match: 'פטריות', dept: D.PRODUCE },
  { match: 'פטריה', dept: D.PRODUCE },
  { match: 'שמפניון', dept: D.PRODUCE },
  { match: 'תפו"ע', dept: D.PRODUCE, priority: 2 },
  { match: 'תפוע', dept: D.PRODUCE, priority: 2 },
  { match: 'רוברב', dept: D.PRODUCE },
  { match: 'תמרים מיובש', dept: D.PRODUCE, priority: 2 },
  { match: 'אבוקדו', dept: D.PRODUCE },
  { match: 'זוקיני', dept: D.PRODUCE },
  { match: 'במיה', dept: D.PRODUCE },
  { match: 'ארטישוק', dept: D.PRODUCE, exclude: ['לבבות ארטישוק', 'ארטישוק קפוא'] },
  { match: 'אספרגוס', dept: D.PRODUCE },
  { match: 'בטטות', dept: D.PRODUCE },
  { match: 'נבטים', dept: D.PRODUCE },
  { match: 'ג׳ינג׳ר', dept: D.PRODUCE },
  { match: 'ג\'ינג\'ר', dept: D.PRODUCE },
  { match: 'זנגביל', dept: D.PRODUCE },
  { match: 'כורכום טרי', dept: D.PRODUCE, priority: 2 },

  // פירות
  { match: 'תפוח', dept: D.PRODUCE, exclude: ['תפוח אדמה', 'תפוא', 'מיץ תפוח', 'חומץ תפוח'] },
  { match: 'בננה', dept: D.PRODUCE },
  { match: 'אבטיח', dept: D.PRODUCE },
  { match: 'מלון', dept: D.PRODUCE },
  { match: 'תות', dept: D.PRODUCE, exclude: ['תות שדה קפוא'] },
  { match: 'ענבים', dept: D.PRODUCE },
  { match: 'אגס', dept: D.PRODUCE },
  { match: 'אפרסק', dept: D.PRODUCE },
  { match: 'נקטרינ', dept: D.PRODUCE },
  { match: 'משמש', dept: D.PRODUCE, exclude: ['ריבת משמש'] },
  { match: 'שזיף', dept: D.PRODUCE },
  { match: 'דובדבן', dept: D.PRODUCE, exclude: ['ריבת דובדבן'] },
  { match: 'תפוז', dept: D.PRODUCE, exclude: ['מיץ תפוז', 'ריבת תפוז'] },
  { match: 'לימון', dept: D.PRODUCE, exclude: ['מיץ לימון', 'מלח לימון', 'חומצת לימון'] },
  { match: 'אשכולית', dept: D.PRODUCE, exclude: ['מיץ אשכולית'] },
  { match: 'מנדרינה', dept: D.PRODUCE },
  { match: 'קלמנטינה', dept: D.PRODUCE },
  { match: 'פומלית', dept: D.PRODUCE },
  { match: 'פומלה', dept: D.PRODUCE },
  { match: 'אננס', dept: D.PRODUCE, exclude: ['מיץ אננס', 'שימורי אננס'] },
  { match: 'מנגו', dept: D.PRODUCE, exclude: ['מיץ מנגו', 'ריבת מנגו'] },
  { match: 'פפאיה', dept: D.PRODUCE },
  { match: 'קיווי', dept: D.PRODUCE },
  { match: 'אפרסמון', dept: D.PRODUCE },
  { match: 'רימון', dept: D.PRODUCE, exclude: ['מיץ רימון', 'ריבת רימון'] },
  { match: 'תאנה', dept: D.PRODUCE, exclude: ['תאנים מיובשות', 'ריבת תאנים'] },
  { match: 'גויאבה', dept: D.PRODUCE },
  { match: 'ליצ\'י', dept: D.PRODUCE },
  { match: 'פסיפלורה', dept: D.PRODUCE },
  { match: 'תמר', dept: D.PRODUCE, exclude: ['סילאן', 'דבש תמרים'] },
  { match: 'תמרים', dept: D.PRODUCE, exclude: ['סילאן', 'דבש תמרים'] },
  { match: 'אוכמני', dept: D.PRODUCE, exclude: ['ריבת אוכמניות'] },
  { match: 'פטל', dept: D.PRODUCE, exclude: ['סירופ פטל', 'ריבת פטל'] },
  { match: 'ליים', dept: D.PRODUCE },
  { match: 'אגוזי קוקוס', dept: D.PRODUCE, priority: 2 },
  { match: 'קוקוס טרי', dept: D.PRODUCE, priority: 2 },
  { match: 'פירות יבשים', dept: D.PRODUCE },
  { match: 'צימוקים', dept: D.PRODUCE },
  { match: 'חמוצים', dept: D.PRODUCE },
  { match: 'זיתים', dept: D.PRODUCE, exclude: ['שמן זית'] },
  { match: 'זית', dept: D.PRODUCE, exclude: ['שמן זית'] },

  // ============================================================
  // מאפייה
  // ============================================================
  { match: 'לחם', dept: D.BAKERY, exclude: ['פירורי לחם', 'אבקת לחם'] },
  { match: 'פיתה', dept: D.BAKERY },
  { match: 'פיתות', dept: D.BAKERY },
  { match: 'לחמני', dept: D.BAKERY },
  { match: 'חלה', dept: D.BAKERY, exclude: ['חלב', 'חלות שבת'] },
  { match: 'חלות', dept: D.BAKERY },
  { match: 'בייגל', dept: D.BAKERY },
  { match: 'בייגלה', dept: D.SNACKS, priority: 2 },
  { match: 'בגט', dept: D.BAKERY },
  { match: 'באגט', dept: D.BAKERY },
  { match: 'קרואסון', dept: D.BAKERY },
  { match: 'רוגלך', dept: D.BAKERY },
  { match: 'מאפה', dept: D.BAKERY },
  { match: 'בורקס', dept: D.FROZEN, priority: 2 },
  { match: 'מאפים', dept: D.BAKERY },
  { match: 'טוסט', dept: D.BAKERY, exclude: ['מצנם'] },
  { match: 'מצה', dept: D.BAKERY },
  { match: 'מצות', dept: D.BAKERY },
  { match: 'לאפה', dept: D.BAKERY },
  { match: 'טורטיה', dept: D.BAKERY },
  { match: 'טורטייה', dept: D.BAKERY },
  { match: 'מלאווח', dept: D.FROZEN, priority: 2 },
  { match: 'ג\'חנון', dept: D.FROZEN, priority: 2 },
  { match: 'עוגיות', dept: D.BAKERY, exclude: ['עוגיות אורז'] },
  { match: 'עוגה', dept: D.BAKERY },
  { match: 'עוגת', dept: D.BAKERY },
  { match: 'מאפין', dept: D.BAKERY },
  { match: 'דונאט', dept: D.BAKERY },
  { match: 'דונט', dept: D.BAKERY },
  { match: 'סופגניה', dept: D.BAKERY },
  { match: 'סופגניות', dept: D.BAKERY },
  { match: 'בריוש', dept: D.BAKERY },
  { match: 'שטרודל', dept: D.BAKERY },

  // ============================================================
  // חלב וביצים
  // ============================================================
  { match: 'חלב', dept: D.DAIRY, exclude: ['חלבון', 'חלב סויה', 'חלב שקדים', 'חלב קוקוס', 'חלבונים', 'אבקת חלב'] },
  { match: 'חלב סויה', dept: D.DAIRY, priority: 2 },
  { match: 'חלב שקדים', dept: D.DAIRY, priority: 2 },
  { match: 'חלב שיבולת שועל', dept: D.DAIRY, priority: 2 },
  { match: 'חלב קוקוס', dept: D.DAIRY, priority: 2 },
  { match: 'גבינה', dept: D.DAIRY },
  { match: 'גבינת', dept: D.DAIRY },
  { match: 'גבינות', dept: D.DAIRY },
  { match: 'קוטג', dept: D.DAIRY },
  { match: 'קוטג\'', dept: D.DAIRY },
  { match: 'יוגורט', dept: D.DAIRY },
  { match: 'דנונה', dept: D.DAIRY },
  { match: 'אקטימל', dept: D.DAIRY },
  { match: 'יופלה', dept: D.DAIRY },
  { match: 'מילקי', dept: D.DAIRY },
  { match: 'מעדן', dept: D.DAIRY },
  { match: 'מעדני', dept: D.DAIRY },
  { match: 'דני', dept: D.DAIRY, exclude: ['דני רובד', 'אדני', 'מודני', 'גורדני', 'יורדני'] },
  { match: 'פודינג', dept: D.DAIRY },
  // Dropped 'גיל' (too many false positives: אביגיל, רגיל, גילון) and 'לבן' as a
  // dairy keyword (color word — clashes with disposables, clothes, paper).
  // Specific dairy items still hit via 'גבינה', 'יוגורט', etc.
  { match: 'לבנה', dept: D.DAIRY, priority: 1, exclude: ['גבינה לבנה', 'שוקולד לבנה'] },
  { match: 'שמנת', dept: D.DAIRY },
  { match: 'חמאה', dept: D.DAIRY, exclude: ['חמאת בוטנים', 'חמאת שקדים', 'חמאת קקאו'] },
  { match: 'מרגרינה', dept: D.DAIRY },
  { match: 'ביצים', dept: D.DAIRY, exclude: ['ביצים פלסטיק'] },
  { match: 'ביצה', dept: D.DAIRY, exclude: ['בצק משחק', 'משחק ביצה', 'ביצה דקורטיב', 'ביצת פסחא דקור'] },
  { match: 'מוצרלה', dept: D.DAIRY },
  { match: 'מוצרללה', dept: D.DAIRY },
  { match: 'פטה', dept: D.DAIRY, exclude: ['שימורי כלב', 'שימורי חתול', 'מזון לכלב', 'מזון לחתול', 'מזון לגור', 'בונזו', 'וונפי'] },
  { match: 'פטה בולגרית', dept: D.DAIRY },
  { match: 'בולגרית', dept: D.DAIRY },
  { match: 'בולגרי', dept: D.DAIRY },
  { match: 'צ\'דר', dept: D.DAIRY },
  { match: 'צדר', dept: D.DAIRY },
  { match: 'גאודה', dept: D.DAIRY },
  { match: 'אמנטל', dept: D.DAIRY },
  { match: 'פרמזן', dept: D.DAIRY },
  { match: 'ריקוטה', dept: D.DAIRY },
  { match: 'מסקרפונה', dept: D.DAIRY },
  { match: 'פילדלפיה', dept: D.DAIRY },
  { match: 'נפוליאון', dept: D.DAIRY, exclude: ['נפוליאון פלפלים', 'נפוליאון זיתים', 'נפוליאון מלפפונ'] },
  { match: 'שמנת חמוצה', dept: D.DAIRY, priority: 2 },
  { match: 'שמנת מתוקה', dept: D.DAIRY, priority: 2 },
  { match: 'גביע', dept: D.DAIRY },
  { match: 'תנובה', dept: D.DAIRY },
  { match: 'טרה', dept: D.DAIRY, exclude: ['פטרה', 'טרי', 'טראפלס', 'תורמטרה', 'אקסטרה', 'אסטרה', 'מטרה'] },
  { match: 'יטבתה', dept: D.DAIRY },
  { match: 'שטראוס', dept: D.DAIRY },
  // Dropped 'גד' as a brand — 2-letter root produces too many false matches.
  { match: 'מולר', dept: D.DAIRY },
  { match: 'אמיגו', dept: D.DAIRY },
  { match: 'גמדים', dept: D.DAIRY },
  { match: 'סקי', dept: D.DAIRY, exclude: ['סקירה', 'סקייט'] },
  { match: 'דיסקית', dept: D.DAIRY },
  { match: 'צפתית', dept: D.DAIRY },
  { match: 'קממבר', dept: D.DAIRY },
  { match: 'גבינה צהובה', dept: D.DAIRY, priority: 2 },

  // ============================================================
  // בשר ועוף ודגים
  // ============================================================
  { match: 'עוף', dept: D.MEAT_FISH, exclude: ['מרק עוף', 'אבקת עוף'] },
  { match: 'חזה עוף', dept: D.MEAT_FISH, priority: 2 },
  { match: 'שוקיים', dept: D.MEAT_FISH },
  { match: 'כרעיים', dept: D.MEAT_FISH },
  { match: 'כנפיים', dept: D.MEAT_FISH },
  { match: 'פרגית', dept: D.MEAT_FISH },
  { match: 'הודו', dept: D.MEAT_FISH },
  { match: 'שניצל', dept: D.MEAT_FISH },
  { match: 'קציצ', dept: D.MEAT_FISH },
  { match: 'קבב', dept: D.MEAT_FISH },
  { match: 'בשר', dept: D.MEAT_FISH, exclude: ['בשר טחון', 'תחליף בשר'] },
  { match: 'בשר טחון', dept: D.MEAT_FISH, priority: 2 },
  { match: 'בקר', dept: D.MEAT_FISH },
  { match: 'אנטריקוט', dept: D.MEAT_FISH },
  { match: 'סינטה', dept: D.MEAT_FISH },
  { match: 'פילה', dept: D.MEAT_FISH },
  { match: 'אונטריב', dept: D.MEAT_FISH },
  { match: 'אסאדו', dept: D.MEAT_FISH },
  { match: 'כבש', dept: D.MEAT_FISH },
  { match: 'כבד', dept: D.MEAT_FISH },
  { match: 'לבבות', dept: D.MEAT_FISH, exclude: ['לבבות ארטישוק', 'לבבות דקל'] },
  { match: 'המבורגר', dept: D.MEAT_FISH },
  { match: 'נקניקיות', dept: D.DELI, priority: 2 },
  { match: 'דג', dept: D.MEAT_FISH, exclude: ['דגים מיובשים', 'דגי קישוט', 'דגיש', 'דגן', 'אבק דגים', 'דגדג'] },
  { match: 'דגים', dept: D.MEAT_FISH },
  { match: 'סלמון', dept: D.MEAT_FISH },
  { match: 'טונה', dept: D.PANTRY, priority: 2 },
  { match: 'טונה טריה', dept: D.MEAT_FISH, priority: 3 },
  { match: 'דניס', dept: D.MEAT_FISH },
  { match: 'מושט', dept: D.MEAT_FISH },
  { match: 'ירכיים', dept: D.MEAT_FISH },
  { match: 'ירך עוף', dept: D.MEAT_FISH, priority: 2 },
  { match: 'שריר הזרוע', dept: D.MEAT_FISH, priority: 2 },
  { match: 'שריר', dept: D.MEAT_FISH, exclude: ['שריר ידיים'] },
  { match: 'אסאדו', dept: D.MEAT_FISH },
  { match: 'פרגיות', dept: D.MEAT_FISH },
  { match: 'פורל', dept: D.MEAT_FISH },
  { match: 'בורי', dept: D.MEAT_FISH },
  { match: 'אמנון', dept: D.MEAT_FISH },
  { match: 'לברק', dept: D.MEAT_FISH },
  { match: 'בקלה', dept: D.MEAT_FISH },
  { match: 'הרינג', dept: D.DELI, priority: 1 },

  // ============================================================
  // דליקטסן
  // ============================================================
  { match: 'נקניק', dept: D.DELI },
  { match: 'נקניקיק', dept: D.DELI },
  { match: 'פסטרמה', dept: D.DELI },
  { match: 'סלמי', dept: D.DELI },
  { match: 'מורטדלה', dept: D.DELI },
  { match: 'בייקון', dept: D.DELI },
  { match: 'פסטרמת', dept: D.DELI },
  { match: 'נקניקיה', dept: D.DELI },
  { match: 'חזיר', dept: D.DELI },
  { match: 'פרושוטו', dept: D.DELI },
  { match: 'קבנוס', dept: D.DELI },
  { match: 'בלקני', dept: D.DELI },
  { match: 'סלט חומוס', dept: D.DELI, priority: 2 },
  { match: 'סלט טחינה', dept: D.DELI, priority: 2 },
  { match: 'סלט חציל', dept: D.DELI, priority: 2 },
  { match: 'מטבוחה', dept: D.DELI },
  { match: 'חרוסת', dept: D.DELI },
  { match: 'סלט מוכן', dept: D.DELI, priority: 2 },

  // ============================================================
  // יבשים ומזווה
  // ============================================================
  { match: 'אורז', dept: D.PANTRY, exclude: ['עוגיות אורז', 'חלב אורז', 'חומץ אורז'] },
  { match: 'פסטה', dept: D.PANTRY },
  { match: 'ספגטי', dept: D.PANTRY },
  { match: 'ספאגטי', dept: D.PANTRY },
  { match: 'מקרוני', dept: D.PANTRY },
  { match: 'פנה', dept: D.PANTRY, exclude: ['פנה ולה', 'דפנה'] },
  { match: 'פוסילי', dept: D.PANTRY },
  { match: 'אטריות', dept: D.PANTRY },
  { match: 'נודלס', dept: D.PANTRY },
  { match: 'קוסקוס', dept: D.PANTRY },
  { match: 'בורגול', dept: D.PANTRY },
  { match: 'פתיתים', dept: D.PANTRY },
  { match: 'קינואה', dept: D.PANTRY },
  { match: 'גריסים', dept: D.PANTRY },
  { match: 'גריסי פנינה', dept: D.PANTRY, priority: 2 },
  { match: 'פריקה', dept: D.PANTRY },
  { match: 'קמח', dept: D.PANTRY },
  { match: 'סוכר', dept: D.PANTRY, exclude: ['סוכריה', 'סוכריות', 'תחליף סוכר'] },
  { match: 'מלח', dept: D.PANTRY, exclude: ['מלחי אמבט', 'מלח לימון'] },
  { match: 'פלפל שחור', dept: D.PANTRY, priority: 2 },
  { match: 'פפריקה', dept: D.PANTRY },
  { match: 'כורכום', dept: D.PANTRY, exclude: ['כורכום טרי'] },
  { match: 'כמון', dept: D.PANTRY },
  { match: 'הל', dept: D.PANTRY, exclude: ['הלל', 'הלך', 'הלכה', 'הלבנה'] },
  { match: 'קינמון', dept: D.PANTRY },
  { match: 'תבלין', dept: D.PANTRY },
  { match: 'תבלינים', dept: D.PANTRY },
  { match: 'אבקת מרק', dept: D.PANTRY, priority: 2 },
  { match: 'מרק', dept: D.PANTRY },
  { match: 'שמן זית', dept: D.PANTRY, priority: 2 },
  { match: 'שמן קנולה', dept: D.PANTRY, priority: 2 },
  { match: 'שמן חמניות', dept: D.PANTRY, priority: 2 },
  { match: 'שמן סויה', dept: D.PANTRY, priority: 2 },
  { match: 'שמן תירס', dept: D.PANTRY, priority: 2 },
  { match: 'שמן', dept: D.PANTRY, exclude: ['שמנת', 'שמנת חמוצה', 'שמן זרעים', 'שמנמן', 'שומשום', 'משומן'] },
  { match: 'חומץ', dept: D.PANTRY },
  { match: 'סויה', dept: D.PANTRY, exclude: ['חלב סויה', 'חלבון סויה'] },
  { match: 'רוטב', dept: D.PANTRY, exclude: ['רוטב סלט'] },
  { match: 'קטשופ', dept: D.PANTRY },
  { match: 'מיונז', dept: D.PANTRY },
  { match: 'חרדל', dept: D.PANTRY },
  { match: 'טחינה', dept: D.PANTRY, exclude: ['סלט טחינה'] },
  { match: 'חומוס', dept: D.PANTRY, exclude: ['סלט חומוס'] },
  { match: 'שעועית', dept: D.PANTRY, exclude: ['שעועית ירוקה'] },
  { match: 'עדשים', dept: D.PANTRY },
  // Dropped 'מש' — 2-letter root matches משקל, השמש, אגם, מאשר, רעמש, in
  // practice almost never the bean. The bean is rare enough to live in
  // user-overrides.
  { match: 'גרגירי חומוס', dept: D.PANTRY, priority: 2 },
  // Dropped 'פול' — 2-letter root matches כפול, אפול, פולנדי, etc.
  { match: 'שימור', dept: D.PANTRY, exclude: ['שימורי כלב', 'שימורי חתול', 'שימורי גור'] },
  // Dropped redundant 'שימורי' rule — 'שימור' already covers it with proper excludes.
  { match: 'רסק עגבני', dept: D.PANTRY, priority: 2 },
  { match: 'ריבה', dept: D.PANTRY },
  { match: 'ממרח', dept: D.PANTRY, exclude: ['ממרח גוף', 'ממרח פנים'] },
  { match: 'דבש', dept: D.PANTRY },
  { match: 'סילאן', dept: D.PANTRY },
  { match: 'נוטלה', dept: D.PANTRY },
  { match: 'ממרח שוקולד', dept: D.PANTRY, priority: 2 },
  { match: 'חמאת בוטנים', dept: D.PANTRY, priority: 2 },
  { match: 'חמאת שקדים', dept: D.PANTRY, priority: 2 },
  { match: 'גרנולה', dept: D.PANTRY },
  { match: 'דגני בוקר', dept: D.PANTRY, priority: 2 },
  { match: 'קורנפלקס', dept: D.PANTRY },
  { match: 'וויטביקס', dept: D.PANTRY },
  { match: 'ויטביקס', dept: D.PANTRY },
  { match: 'ברנפלקס', dept: D.PANTRY },
  { match: 'דגני', dept: D.PANTRY, exclude: ['קינדר שוקולד עם דגנים'] },
  { match: 'צ\'יריוס', dept: D.PANTRY },
  { match: 'קוואקר', dept: D.PANTRY },
  { match: 'שיבולת שועל', dept: D.PANTRY, exclude: ['חלב שיבולת שועל'] },
  { match: 'גרעיני', dept: D.PANTRY },
  { match: 'גרעינים', dept: D.PANTRY },
  { match: 'חמניות', dept: D.PANTRY, exclude: ['שמן חמניות'] },
  { match: 'אגוזים', dept: D.PANTRY, exclude: ['חמאת אגוזים'] },
  { match: 'אגוזי מלך', dept: D.PANTRY, priority: 2 },
  { match: 'אגוזי לוז', dept: D.PANTRY, priority: 2 },
  { match: 'שקדים', dept: D.PANTRY, exclude: ['חלב שקדים', 'חמאת שקדים'] },
  { match: 'שקד מולבן', dept: D.PANTRY, priority: 2 },
  { match: 'שקד קלוי', dept: D.PANTRY, priority: 2 },
  { match: 'כוסמת', dept: D.PANTRY },
  { match: 'בוטנים', dept: D.PANTRY, exclude: ['חמאת בוטנים'] },
  { match: 'פיסטוק', dept: D.PANTRY },
  { match: 'פיסטוקים', dept: D.PANTRY },
  { match: 'קשיו', dept: D.PANTRY },
  { match: 'אגוז פקאן', dept: D.PANTRY, priority: 2 },
  { match: 'פצפוצי אורז', dept: D.PANTRY, priority: 2 },
  { match: 'סירופ', dept: D.PANTRY, exclude: ['סירופ פטל', 'סירופ שיעול'] },
  { match: 'מייפל', dept: D.PANTRY },
  { match: 'תערובת', dept: D.PANTRY, priority: 1 },
  { match: 'שקדי מרק', dept: D.PANTRY, priority: 2 },
  { match: 'אטריות אינסטנט', dept: D.PANTRY, priority: 2 },
  { match: 'נודלס אינסטנט', dept: D.PANTRY, priority: 2 },
  { match: 'ארוחת נודלס', dept: D.PANTRY, priority: 2 },
  { match: 'מאסטר שף', dept: D.PANTRY },
  { match: 'איטריות', dept: D.PANTRY },
  { match: 'איטריות אורז', dept: D.PANTRY, priority: 2 },
  { match: 'נמס בכוס', dept: D.BEVERAGES, priority: 2 },
  { match: 'פסטו', dept: D.PANTRY, exclude: ['ממרח פסטו'] },
  { match: 'ממרח פסטו', dept: D.PANTRY, priority: 2 },
  { match: 'רסק תפוח', dept: D.PANTRY, priority: 2 },
  { match: 'עלי גפן', dept: D.PANTRY, priority: 2 },
  { match: 'דגנים', dept: D.PANTRY, exclude: ['קינדר שוקולד עם דגנים'] },
  { match: 'גרגירי', dept: D.PANTRY },
  { match: 'אבקת אפיה', dept: D.PANTRY },
  { match: 'שמרים', dept: D.PANTRY },
  { match: 'תמצית וניל', dept: D.PANTRY, priority: 2 },
  { match: 'וניל', dept: D.PANTRY, exclude: ['גלידת וניל', 'יוגורט וניל'] },
  { match: 'שוקולית', dept: D.PANTRY },
  { match: 'אבקת קקאו', dept: D.PANTRY, priority: 2 },
  { match: 'קקאו', dept: D.PANTRY },
  { match: 'קוקוס', dept: D.PANTRY, exclude: ['חלב קוקוס', 'שמן קוקוס', 'מים קוקוס', 'קרם קוקוס', 'קוקוס טרי', 'אגוזי קוקוס'] },
  { match: 'מרווה', dept: D.PANTRY, exclude: ['מרוות'] },
  { match: 'ציה', dept: D.PANTRY, exclude: ['ציות', 'ציין'] },
  { match: 'זרעי ציה', dept: D.PANTRY, priority: 2 },
  { match: 'זרעי פשתן', dept: D.PANTRY, priority: 2 },
  { match: 'זרעי דלעת', dept: D.PANTRY, priority: 2 },
  { match: 'גרעיני חמניות', dept: D.PANTRY, priority: 2 },
  { match: 'אבקת סוכר', dept: D.PANTRY, priority: 2 },
  { match: 'סוכר חום', dept: D.PANTRY, priority: 2 },
  { match: 'סוכר ונילי', dept: D.PANTRY, priority: 2 },
  { match: 'ג\'לטין', dept: D.PANTRY },
  { match: 'אבקת ג\'לי', dept: D.PANTRY, priority: 2 },
  { match: 'ג\'לי', dept: D.PANTRY, exclude: ['ג\'ל'] },
  { match: 'פתי בר', dept: D.SNACKS, priority: 2 },
  { match: 'קרקרים', dept: D.SNACKS, priority: 2 },
  { match: 'מצות יצהר', dept: D.SNACKS, priority: 2 },
  // Dropped 'אסם' as a brand — they make snacks (Bisli/Bamba) too, so the
  // brand alone isn't predictive. Specific products still hit via 'במבה',
  // 'ביסלי', 'אטריות' etc.
  { match: 'תלמה', dept: D.PANTRY },

  // ============================================================
  // חטיפים ומתוקים
  // ============================================================
  { match: 'במבה', dept: D.SNACKS },
  { match: 'ביסלי', dept: D.SNACKS },
  { match: 'צ\'יפס', dept: D.SNACKS, exclude: ['פיש אנד צ\'יפס', 'צ\'יפס תפוח אדמה קפוא'] },
  { match: 'תפוצ\'יפס', dept: D.SNACKS },
  { match: 'דוריטוס', dept: D.SNACKS },
  { match: 'צ\'יטוס', dept: D.SNACKS },
  { match: 'אפרופו', dept: D.SNACKS },
  { match: 'שוגי', dept: D.SNACKS },
  { match: 'מסטיק', dept: D.SNACKS },
  { match: 'סוכריות', dept: D.SNACKS },
  { match: 'סוכריה', dept: D.SNACKS },
  { match: 'טופי', dept: D.SNACKS, exclude: ['טופיק'] },
  { match: 'דובוני', dept: D.SNACKS },
  { match: 'גומי', dept: D.SNACKS, exclude: ['כפפות גומי', 'שטיח גומי'] },
  { match: 'שוקולד', dept: D.SNACKS, exclude: ['ממרח שוקולד', 'שוקולד למאפה', 'חמאת קקאו'] },
  // 'שוקו' is the chilled chocolate-milk drink — DAIRY. Must exclude 'שוקולד'
  // because 'שוקו' is a substring of 'שוקולד'.
  { match: 'שוקו', dept: D.DAIRY, exclude: ['שוקולד'] },
  { match: 'פרלין', dept: D.SNACKS },
  { match: 'ופל', dept: D.SNACKS },
  { match: 'ופלים', dept: D.SNACKS },
  { match: 'קרמבו', dept: D.SNACKS },
  { match: 'עוגיות שוקולד', dept: D.SNACKS, priority: 2 },
  { match: 'מנצ\'יז', dept: D.SNACKS },
  { match: 'מיני מאפה', dept: D.SNACKS, priority: 2 },
  { match: 'חטיף', dept: D.SNACKS },
  { match: 'חטיפי', dept: D.SNACKS },
  { match: 'קליק', dept: D.SNACKS },
  { match: 'פררו', dept: D.SNACKS },
  { match: 'קינדר', dept: D.SNACKS },
  { match: 'מילקה', dept: D.SNACKS },
  // 'עלית' makes both chocolate and coffee. Drop the brand-level rule; specific
  // products (פסק זמן, מקופלת, קפה עלית) hit via their own keywords.
  { match: 'מקופלת', dept: D.SNACKS },
  { match: 'פסק זמן', dept: D.SNACKS },
  { match: 'אגו', dept: D.SNACKS, exclude: ['אגוז', 'אגודל', 'אגודה'] },
  { match: 'טוויסט', dept: D.SNACKS },
  { match: 'באבא', dept: D.SNACKS },
  { match: 'לוטוס', dept: D.SNACKS, exclude: ['לוטוס לבנה'] },
  { match: 'אוראו', dept: D.SNACKS },
  { match: 'אוריאו', dept: D.SNACKS },
  { match: 'מקרון', dept: D.SNACKS, exclude: ['מקרוני'] },
  { match: 'חלבה', dept: D.SNACKS, priority: 1 },
  { match: 'לוקום', dept: D.SNACKS },
  { match: 'מרשמלו', dept: D.SNACKS },
  { match: 'טיק טק', dept: D.SNACKS, priority: 2 },
  { match: 'מנטוס', dept: D.SNACKS },
  { match: 'באונטי', dept: D.SNACKS },
  { match: 'מארס', dept: D.SNACKS, exclude: ['מארס שוקו'] },
  { match: 'סניקרס', dept: D.SNACKS },
  { match: 'טוורקס', dept: D.SNACKS },
  { match: 'טוויקס', dept: D.SNACKS },
  { match: 'מקסימוס', dept: D.SNACKS },
  { match: 'נשנושים', dept: D.SNACKS },
  { match: 'נאצ\'וס', dept: D.SNACKS },
  { match: 'נאצוס', dept: D.SNACKS },
  { match: 'פפיטס', dept: D.SNACKS },
  { match: 'בפלות', dept: D.SNACKS },
  { match: 'בייגלה דקים', dept: D.SNACKS, priority: 2 },
  { match: 'מרציפן', dept: D.SNACKS },
  { match: 'ציפס גלי', dept: D.SNACKS, priority: 2 },
  { match: 'טוסו', dept: D.SNACKS },
  { match: 'צוקטה', dept: D.SNACKS },
  { match: 'צ\'וקולטה', dept: D.SNACKS },
  { match: 'צוקולטה', dept: D.SNACKS },
  { match: 'היידי', dept: D.SNACKS },
  { match: 'לינדט', dept: D.SNACKS },
  { match: 'לינדור', dept: D.SNACKS },
  { match: 'טוניס', dept: D.SNACKS },
  { match: 'אגדה', dept: D.SNACKS },
  { match: 'טבלת שוקולד', dept: D.SNACKS, priority: 2 },
  { match: 'שוקולד מריר', dept: D.SNACKS, priority: 2 },
  { match: 'שוקולד חלב', dept: D.SNACKS, priority: 2 },
  { match: 'שוקולד לבן', dept: D.SNACKS, priority: 2 },
  { match: 'באבא', dept: D.SNACKS, exclude: ['באבא גנוש'] },

  // ============================================================
  // משקאות
  // ============================================================
  { match: 'מיץ', dept: D.BEVERAGES },
  { match: 'מי טבעי', dept: D.BEVERAGES, priority: 2 },
  { match: 'מים מינרל', dept: D.BEVERAGES, priority: 2 },
  { match: 'מים מינרלים', dept: D.BEVERAGES, priority: 2 },
  { match: 'מי עדן', dept: D.BEVERAGES, priority: 2 },
  { match: 'מים', dept: D.BEVERAGES, exclude: ['מי טבעת', 'מים חמים', 'אדים', 'מים מטוהרים'] },
  { match: 'סודה', dept: D.BEVERAGES, exclude: ['אבקת סודה', 'סודה לשתיה'] },
  { match: 'קולה', dept: D.BEVERAGES, exclude: ['קולה חמה', 'קולה ברד'] },
  { match: 'קוקה קולה', dept: D.BEVERAGES, priority: 2 },
  { match: 'פפסי', dept: D.BEVERAGES },
  { match: 'ספרייט', dept: D.BEVERAGES },
  { match: 'פאנטה', dept: D.BEVERAGES },
  { match: 'פנטה', dept: D.BEVERAGES },
  { match: 'שוופס', dept: D.BEVERAGES },
  { match: 'נסטי', dept: D.BEVERAGES },
  { match: 'פריגת', dept: D.BEVERAGES },
  { match: 'פריגו', dept: D.BEVERAGES },
  { match: 'פיוז טי', dept: D.BEVERAGES },
  { match: 'XL', dept: D.BEVERAGES },
  { match: 'רד בול', dept: D.BEVERAGES },
  { match: 'משקה אנרגיה', dept: D.BEVERAGES, priority: 2 },
  { match: 'גמבה', dept: D.BEVERAGES },
  { match: 'קפה נמס', dept: D.BEVERAGES, priority: 2 },
  { match: 'קפה שחור', dept: D.BEVERAGES, priority: 2 },
  { match: 'קפה הפוך', dept: D.BEVERAGES, priority: 2 },
  { match: 'קפה טורקי', dept: D.BEVERAGES, priority: 2 },
  { match: 'קפסולות קפה', dept: D.BEVERAGES, priority: 2 },
  { match: 'קפה', dept: D.BEVERAGES, priority: 1, exclude: ['גלידת קפה', 'עוגת קפה', 'בית קפה'] },
  { match: 'נסקפה', dept: D.BEVERAGES },
  { match: 'תה', dept: D.BEVERAGES, exclude: ['תה ירוק קפוא', 'תהילה', 'תהום', 'תהליך', 'תהיה', 'תהומי'] },
  { match: 'נוטרינו', dept: D.BEVERAGES },
  { match: 'משקה צמחי', dept: D.BEVERAGES, priority: 2 },
  { match: 'חליטת', dept: D.BEVERAGES, priority: 2 },
  { match: 'חליטה', dept: D.BEVERAGES, priority: 2 },
  { match: 'ליפטון', dept: D.BEVERAGES },
  { match: 'קמומיל', dept: D.BEVERAGES },
  { match: 'משקה מוגז', dept: D.BEVERAGES, priority: 2 },
  { match: 'משקה קל', dept: D.BEVERAGES, priority: 2 },
  { match: 'משקה אורז', dept: D.BEVERAGES, priority: 2 },
  { match: 'משקה סויה', dept: D.BEVERAGES, priority: 2 },
  { match: 'שייק', dept: D.BEVERAGES, exclude: ['שייקר', 'אפטר שייב'] },
  { match: 'משקה קפה', dept: D.BEVERAGES, priority: 2 },
  { match: 'אפרול', dept: D.ALCOHOL },
  { match: 'אסטי', dept: D.ALCOHOL, exclude: ['אסטוניש'] },
  { match: 'נמס אייס', dept: D.BEVERAGES, priority: 2 },
  { match: 'קוקטייל', dept: D.ALCOHOL, exclude: ['קוקטייל קוסמופוליטן ללא'] },

  // ============================================================
  // אלכוהול
  // ============================================================
  { match: 'יין', dept: D.ALCOHOL, exclude: ['חומץ יין'] },
  { match: 'יינות', dept: D.ALCOHOL },
  { match: 'בירה', dept: D.ALCOHOL },
  { match: 'וודקה', dept: D.ALCOHOL },
  { match: 'וויסקי', dept: D.ALCOHOL },
  { match: 'ויסקי', dept: D.ALCOHOL },
  { match: 'ערק', dept: D.ALCOHOL },
  { match: 'טקילה', dept: D.ALCOHOL },
  { match: 'רום', dept: D.ALCOHOL },
  { match: 'ליקר', dept: D.ALCOHOL },
  { match: 'שמפנייה', dept: D.ALCOHOL },
  { match: 'גין', dept: D.ALCOHOL, exclude: ['ג\'ינג\'ר', 'מרגרין'] },
  { match: 'ברנדי', dept: D.ALCOHOL },
  { match: 'קוניאק', dept: D.ALCOHOL },
  { match: 'אבסולוט', dept: D.ALCOHOL },
  { match: 'יוניברסל', dept: D.ALCOHOL },
  { match: 'מאלט', dept: D.ALCOHOL },
  { match: 'גולדסטאר', dept: D.ALCOHOL },
  { match: 'מכבי', dept: D.ALCOHOL, exclude: ['מכבי האש'] },
  { match: 'קרלסברג', dept: D.ALCOHOL },
  { match: 'היינקן', dept: D.ALCOHOL },
  { match: 'טובורג', dept: D.ALCOHOL },
  { match: 'ערדל', dept: D.ALCOHOL },

  // ============================================================
  // קפואים
  // ============================================================
  { match: 'גלידה', dept: D.FROZEN },
  { match: 'גלידת', dept: D.FROZEN },
  { match: 'ארטיק', dept: D.FROZEN },
  { match: 'שלגון', dept: D.FROZEN },
  { match: 'בלינצ\'ס', dept: D.FROZEN },
  { match: 'בלינצס', dept: D.FROZEN },
  { match: 'פיצה קפואה', dept: D.FROZEN, priority: 2 },
  { match: 'פיצה', dept: D.FROZEN, exclude: ['פיצה חמה', 'תבלין פיצה'] },
  { match: 'קפוא', dept: D.FROZEN },
  { match: 'קפואים', dept: D.FROZEN },
  { match: 'קפואה', dept: D.FROZEN },
  { match: 'מאגלי', dept: D.FROZEN },
  { match: 'אגרול', dept: D.FROZEN },
  { match: 'גיוזה', dept: D.FROZEN },
  { match: 'דים סאם', dept: D.FROZEN },
  { match: 'פלאפל קפוא', dept: D.FROZEN, priority: 2 },
  { match: 'קרוקטים', dept: D.FROZEN },
  { match: 'בצק עלים', dept: D.FROZEN, priority: 2 },
  { match: 'בצק', dept: D.FROZEN, exclude: ['בצק משחק', 'בצק לסליים'] },
  { match: 'מיני בורקס', dept: D.FROZEN, priority: 2 },
  { match: 'קרפלך', dept: D.FROZEN },
  { match: 'פלאפל', dept: D.FROZEN },
  { match: 'שניצל קפוא', dept: D.FROZEN, priority: 2 },
  { match: 'ירקות קפואים', dept: D.FROZEN, priority: 2 },
  { match: 'אפונה קפואה', dept: D.FROZEN, priority: 2 },
  { match: 'תות קפוא', dept: D.FROZEN, priority: 2 },
  { match: 'סולרו', dept: D.FROZEN },
  { match: 'פופסטאר', dept: D.FROZEN },
  { match: 'מגנום', dept: D.FROZEN },
  { match: 'קורנטו', dept: D.FROZEN },
  { match: 'טחון מהצומח', dept: D.MEAT_FISH, priority: 2 },

  // ============================================================
  // ניקיון
  // ============================================================
  { match: 'סבון כלים', dept: D.CLEANING, priority: 2 },
  { match: 'נוזל כלים', dept: D.CLEANING, priority: 2 },
  { match: 'פיירי', dept: D.CLEANING },
  { match: 'סוד', dept: D.CLEANING, exclude: ['סודה', 'סודיום'] },
  { match: 'אקונומיקה', dept: D.CLEANING },
  { match: 'כלורקס', dept: D.CLEANING },
  { match: 'אקונומי', dept: D.CLEANING },
  { match: 'מטהר', dept: D.CLEANING },
  { match: 'מטהרים', dept: D.CLEANING },
  { match: 'אבקת כביסה', dept: D.CLEANING, priority: 2 },
  { match: 'נוזל כביסה', dept: D.CLEANING, priority: 2 },
  { match: 'מרכך כביסה', dept: D.CLEANING, priority: 2 },
  { match: 'כביסה', dept: D.CLEANING },
  { match: 'אריאל', dept: D.CLEANING },
  { match: 'פרסיל', dept: D.CLEANING },
  { match: 'בדין', dept: D.CLEANING },
  { match: 'סנו', dept: D.CLEANING, exclude: ['סנופי'] },
  { match: 'ספונג\'ה', dept: D.CLEANING },
  { match: 'ספוג', dept: D.CLEANING },
  { match: 'ספוגים', dept: D.CLEANING },
  { match: 'מטליות', dept: D.CLEANING },
  { match: 'מטלית', dept: D.CLEANING },
  { match: 'נייר טואלט', dept: D.CLEANING, priority: 2 },
  { match: 'טואלט', dept: D.CLEANING },
  { match: 'נייר מטבח', dept: D.CLEANING, priority: 2 },
  { match: 'מגבוני', dept: D.CLEANING, exclude: ['מגבוני תינוק', 'מגבוני פנים'] },
  { match: 'מגבונים', dept: D.CLEANING, exclude: ['מגבוני תינוק', 'מגבוני פנים'] },
  { match: 'שקיות אשפה', dept: D.CLEANING, priority: 2 },
  { match: 'שקיות', dept: D.CLEANING },
  { match: 'אבק', dept: D.CLEANING, exclude: ['אבקת חלב', 'אבקת סוכר', 'אבקת אפיה', 'אבקת קקאו', 'אבקת מרק', 'אבקת ג\'לי', 'אבקת כביסה', 'אבקת סודה', 'אבק לשעון'] },
  { match: 'מנקה', dept: D.CLEANING },
  { match: 'ניקוי', dept: D.CLEANING },
  { match: 'מסיר כתמים', dept: D.CLEANING, priority: 2 },
  { match: 'מי כביסה', dept: D.CLEANING, priority: 2 },
  { match: 'נייר אלומיניום', dept: D.CLEANING, priority: 2 },
  { match: 'אלומיניום', dept: D.CLEANING },
  { match: 'ניילון נצמד', dept: D.CLEANING, priority: 2 },
  { match: 'נר', dept: D.CLEANING, exclude: ['נרגילה'] },
  { match: 'נרות', dept: D.CLEANING },
  { match: 'גפרור', dept: D.CLEANING },
  { match: 'מצית', dept: D.CLEANING },
  { match: 'סוללה', dept: D.CLEANING },
  { match: 'סוללות', dept: D.CLEANING },
  { match: 'נורה', dept: D.CLEANING, exclude: ['נורווגיה'] },
  { match: 'נורות', dept: D.CLEANING },
  { match: 'כלי חד פעמי', dept: D.CLEANING, priority: 2 },
  { match: 'חד פעמי', dept: D.CLEANING },
  { match: 'חד-פעמי', dept: D.CLEANING },
  { match: 'צלחות חד פעמי', dept: D.CLEANING, priority: 2 },
  { match: 'כוסות חד פעמי', dept: D.CLEANING, priority: 2 },
  { match: 'סכו"ם חד פעמי', dept: D.CLEANING, priority: 2 },
  { match: 'נייר אפיה', dept: D.CLEANING, priority: 2 },
  { match: 'מטף', dept: D.CLEANING },
  { match: 'דאודורנט מקרר', dept: D.CLEANING, priority: 3 },
  { match: 'מרסס', dept: D.CLEANING },
  { match: 'נוזל רצפות', dept: D.CLEANING, priority: 2 },
  { match: 'רצפות', dept: D.CLEANING },
  { match: 'דטול', dept: D.CLEANING },
  { match: 'דזיטול', dept: D.CLEANING },
  { match: 'קלגון', dept: D.CLEANING },
  { match: 'אסטוניש', dept: D.CLEANING },
  { match: 'קפסולות', dept: D.CLEANING, exclude: ['קפסולות קפה'] },
  { match: 'מפת שולחן', dept: D.CLEANING, priority: 2 },
  { match: 'מפיות', dept: D.CLEANING },
  { match: 'תחליב רחיצה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'מבשם', dept: D.CLEANING },
  { match: 'מבשמים', dept: D.CLEANING },
  { match: 'תרסיס חיטוי', dept: D.CLEANING, priority: 2 },
  { match: 'חיטוי', dept: D.CLEANING },
  { match: 'מטף', dept: D.CLEANING },
  { match: 'מי כלים', dept: D.CLEANING, priority: 2 },
  { match: 'מטאטא', dept: D.CLEANING },
  { match: 'יעה', dept: D.CLEANING, exclude: ['בייקאו', 'אגוז ידע'] },
  { match: 'דלי', dept: D.CLEANING, exclude: ['דליה', 'דליות', 'דליל', 'דליפ', 'דליק'] },
  { match: 'קשים', dept: D.CLEANING, exclude: ['קשים הר'] },
  { match: 'כוסות חד', dept: D.CLEANING, priority: 2 },
  { match: 'מזלג חד', dept: D.CLEANING, priority: 2 },
  { match: 'מזלגות', dept: D.CLEANING },
  { match: 'כפיות חד', dept: D.CLEANING, priority: 2 },
  { match: 'מיני מזלג', dept: D.CLEANING, priority: 2 },
  { match: 'כפית פלסטיק', dept: D.CLEANING, priority: 2 },

  // ============================================================
  // פארם וטיפוח
  // ============================================================
  { match: 'שמפו', dept: D.PERSONAL_CARE },
  { match: 'מרכך שיער', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'מרכך', dept: D.PERSONAL_CARE, exclude: ['מרכך כביסה'] },
  { match: 'דאודורנט', dept: D.PERSONAL_CARE, exclude: ['דאודורנט מקרר'] },
  { match: 'משחת שיניים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'מברשת שיניים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'חוט דנטלי', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'מי פה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'ליסטרין', dept: D.PERSONAL_CARE },
  { match: 'סבון רחצה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'סבון פנים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'סבון ידיים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'תכשיר רחצה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'ג\'ל רחצה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'תחליב רחצה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קרם גוף', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קרם ידיים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קרם פנים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קרם הגנה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קרם לחות', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'הגנה מהשמש', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'הגנה מפני השמש', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'spf', dept: D.PERSONAL_CARE },
  { match: 'קר.לחות', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'קר.הגנה', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'פאלטה', dept: D.PERSONAL_CARE },
  { match: 'מטרייה', dept: D.PERSONAL_CARE, exclude: ['מטריה לגשם'] },
  { match: 'בלונס', dept: D.PERSONAL_CARE },
  { match: 'קרם', dept: D.PERSONAL_CARE, exclude: ['קרם חמוץ', 'קרם ברולה', 'גלידת קרם', 'עוגת קרם', 'כפית קרם', 'כפיות קרם', 'קרם פטיסייר', 'קרם להכנה'] },
  { match: 'בושם', dept: D.PERSONAL_CARE },
  { match: 'אפטר שייב', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'תער', dept: D.PERSONAL_CARE, exclude: ['תערובת', 'תערוב', 'תערוכה'] },
  { match: 'סכין גילוח', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'גילוח', dept: D.PERSONAL_CARE, exclude: ['סכין גילוח'] },
  { match: 'ניקול', dept: D.PERSONAL_CARE },
  { match: 'דאב', dept: D.PERSONAL_CARE, exclude: ['דאבל', 'לינדור דאבל'] },
  { match: 'דאו', dept: D.PERSONAL_CARE, exclude: ['דאוס'] },
  { match: 'ניווה', dept: D.PERSONAL_CARE },
  { match: 'ניוואה', dept: D.PERSONAL_CARE },
  { match: 'פלמוליב', dept: D.PERSONAL_CARE },
  { match: 'קרליין', dept: D.PERSONAL_CARE },
  { match: 'אלביב', dept: D.PERSONAL_CARE },
  { match: 'סבון', dept: D.PERSONAL_CARE, exclude: ['סבון כלים', 'נוזל כלים', 'סבון לבן'] },
  { match: 'אקסס', dept: D.PERSONAL_CARE },
  { match: 'ראש וכתפיים', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'פנטן', dept: D.PERSONAL_CARE },
  { match: 'תחבושת', dept: D.PERSONAL_CARE },
  { match: 'תחבושות', dept: D.PERSONAL_CARE },
  { match: 'טמפון', dept: D.PERSONAL_CARE },
  { match: 'טמפונים', dept: D.PERSONAL_CARE },
  { match: 'טוש', dept: D.PERSONAL_CARE, exclude: ['טוסט', 'טושים', 'טוש לבית ספר'] },
  { match: 'ויטמין', dept: D.PERSONAL_CARE },
  { match: 'ויטמינים', dept: D.PERSONAL_CARE },
  { match: 'אקמול', dept: D.PERSONAL_CARE },
  { match: 'אדויל', dept: D.PERSONAL_CARE },
  { match: 'נורופן', dept: D.PERSONAL_CARE },
  { match: 'אופטלגין', dept: D.PERSONAL_CARE },
  { match: 'פלסטר', dept: D.PERSONAL_CARE },
  { match: 'פלסטרים', dept: D.PERSONAL_CARE },
  { match: 'אקמולי', dept: D.PERSONAL_CARE },
  { match: 'נוסטרילה', dept: D.PERSONAL_CARE },
  { match: 'משחה', dept: D.PERSONAL_CARE, exclude: ['משחת שיניים', 'משחת שזיפים'] },
  { match: 'מסיכה', dept: D.PERSONAL_CARE },
  { match: 'איפור', dept: D.PERSONAL_CARE },
  // 'לק' was too short and matched אללק, פמלי לקשרי, ברנפלקס, פלסטיק, פסטו אוללק.
  // Replaced by specific phrases below.
  { match: 'לק שקוף', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'לק ציפורנ', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'מסיר לק', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'פדים להסרת איפור', dept: D.PERSONAL_CARE, priority: 2 },
  { match: 'פדים להסרת', dept: D.PERSONAL_CARE, priority: 1 },

  // ============================================================
  // תינוקות
  // ============================================================
  { match: 'חיתול', dept: D.BABY },
  { match: 'חיתולים', dept: D.BABY },
  { match: 'האגיס', dept: D.BABY },
  { match: 'פמפרס', dept: D.BABY },
  { match: 'מטרנה', dept: D.BABY },
  { match: 'סימילק', dept: D.BABY },
  { match: 'נוטרילון', dept: D.BABY },
  { match: 'תמ"ל', dept: D.BABY },
  { match: 'תמל', dept: D.BABY, exclude: ['תמלא', 'תמלוג'] },
  { match: 'מזון תינוקות', dept: D.BABY, priority: 2 },
  { match: 'מחית', dept: D.BABY },
  { match: 'מחיות', dept: D.BABY },
  { match: 'מגבוני תינוק', dept: D.BABY, priority: 3 },
  { match: 'מוצץ', dept: D.BABY },
  { match: 'בקבוק תינוק', dept: D.BABY, priority: 2 },
  { match: 'פטרוס', dept: D.BABY },
  { match: 'גמדי', dept: D.BABY, exclude: ['גמדים'] },
  { match: 'תינוק', dept: D.BABY },
  { match: 'תינוקות', dept: D.BABY },
];

// ---------------------------------------------------------------------------
// Classifier
// ---------------------------------------------------------------------------

/** Strip Hebrew niqqud and collapse whitespace. */
function normalize(name: string): string {
  return name
    .normalize('NFKC')
    .replace(/[֑-ׇ]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

export interface ClassificationResult {
  department: DepartmentCode;
  matchedRule: string | null;
}

export function classifyItem(name: string | null | undefined): ClassificationResult {
  if (!name) return { department: DEPARTMENT_CODES.UNCLASSIFIED, matchedRule: null };
  const text = normalize(name);
  if (!text) return { department: DEPARTMENT_CODES.UNCLASSIFIED, matchedRule: null };

  let best: { rule: Rule; score: number } | null = null;

  for (const rule of RULES) {
    const m = normalize(rule.match);
    if (!text.includes(m)) continue;
    if (rule.exclude?.some((ex) => text.includes(normalize(ex)))) continue;

    const score = (rule.priority ?? 0) * 1000 + m.length;
    if (!best || score > best.score) best = { rule, score };
  }

  if (!best) return { department: DEPARTMENT_CODES.UNCLASSIFIED, matchedRule: null };
  return { department: best.rule.dept, matchedRule: best.rule.match };
}

export function classifyToDepartmentCode(name: string | null | undefined): DepartmentCode {
  return classifyItem(name).department;
}
